on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy website to production server
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./cicd/deploy.sh
      - run: |
          KEY=${{ secrets.KEY }} \
          USERNAME=${{ secrets.USERNAME }} \
          HOST=${{ secrets.HOST }} \
            ./cicd/deploy.sh
