name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy website to production server

    steps:
      - uses: actions/checkout@v3

      - name: Format, check, lint and build
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        run: |
          npm i
          npm run format
          npm run check
          npm run lint

      - name: Copy website static files over via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: 'build/*'
          target: '/www/personal_website'
