on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy website to production server
    runs-on: ubuntu-latest
    env:
      KEY: ${{ secrets.KEY }}
      USERNAME: ${{ secrets.USERNAME }}
      HOST: ${{ secrets.HOST }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install golang openssh-client
      - run: chmod +x ./cicd/deploy.sh
      - run: ./cicd/deploy.sh
